App/urls.py
from django.contrib import admin
from django.urls import path, include

from Authentication.views import LoginView, LogoutView
from Core.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('', HomeView.as_view(), name='home'),
    path('search/', include("Edupage.urls")),
    path('reservations/', include("Reservation.urls")),
]
'''urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'docs', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path(r'debug', include(debug_toolbar.urls))

]'''

Reservation/urls.py
from django.urls import path

from Reservation.views import *

urlpatterns = [
    path('', ReservationListView.as_view(), name="reservation-list"),
    path('create/', ReservationCreateView.as_view(), name='reservation-create'),
    path('delete/', ReservationDeleteView.as_view(), name="reservation-delete"),
    path('<int:id>/', ReservationDetailView.as_view(), name="reservation-detail"),
]

Classroom/models.py
# Create your models here.
from django.db import models

from Classroom.equipment_enum import Equipment


class Classroom(models.Model):
    id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=30, unique=True)
    position = models.CharField(max_length=30)
    interactive_board = models.BooleanField()
    teacher_pc = models.BooleanField()
    teacher_notebook = models.BooleanField()
    flip_chart = models.BooleanField()
    sink = models.BooleanField()
    data_projector = models.BooleanField()
    ethernet_cable = models.BooleanField()

    class Meta:
        db_table = "Classrooms"

    def __str__(self):
        return f'{self.name} {self.position}'

    def get_dict(self):
        return {
            "id": self.id,
            "name": self.name,
            "position": self.position,
            "equipment": {
                Equipment.INTERACTIVE_BOARD.value[1]: self.interactive_board,
                Equipment.PC.value[1]: self.teacher_pc,
                Equipment.NOTEBOOK.value[1]: self.teacher_notebook,
                Equipment.FLIP_CHART.value[1]: self.flip_chart,
                Equipment.SINK.value[1]: self.sink,
                Equipment.DATA_PROJECTOR.value[1]: self.data_projector,
                Equipment.ETHERNET_CABLE.value[1]: self.ethernet_cable,
            }

        }

Reservation/models.py
from django.db import models


# Create your models here.
from Classroom.models import Classroom


class Reservation(models.Model):
    id = models.BigAutoField(primary_key=True)
    date = models.DateField()
    classroom = models.ForeignKey(Classroom, on_delete=models.CASCADE)
    lesson = models.IntegerField()
    teacher = models.CharField(max_length=30)

    class Meta:
        unique_together = ("date", "lesson", "classroom")
        db_table = "Reservations"

    def __str__(self):
        return f'{self.date} {self.classroom} {self.lesson} {self.teacher}'

Reservation/views.py
# Create your views here.
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from django.views import View

from Classroom.models import Classroom
from Core.functions import is_classroom_available
from Edupage.views import parse_inputs
from Reservation.models import Reservation


class ReservationBaseView(View):
    model = Reservation
    fields = '__all__'


class ReservationListView(View):
    @method_decorator(login_required, name='dispatch')
    def get(self, request, *args):
        teacher = f'{request.user.first_name} {request.user.last_name}'
        if request.user.is_superuser:
            reservations = Reservation.objects.all().order_by('date')
        else:
            reservations = Reservation.objects.filter(teacher=teacher).order_by('date')

        context = {
            "reservations": reservations
        }
        return render(request, "reservation_list.html", context)


class ReservationCreateView(View):
    @method_decorator(login_required, name='dispatch')
    def get(self, request, *args, **kwargs):
        input_date, input_lesson, input_room_id, _, parsing_error = parse_inputs(
            REST_method=request.GET)
        if not parsing_error["is_valid"]:
            messages.error(request, parsing_error["errors"][0])
            return redirect('search')
        if (input_date is None) or (input_lesson is None) or (input_room_id is None):
            messages.error(request, "Chýbajúce argumenty (dátum, učebňa alebo hodina) pre rezerváciu učebne.")
            return redirect('search')
        teacher = f'{request.user.first_name} {request.user.last_name}'
        classroom = None
        try:
            classroom = Classroom.objects.get(id=input_room_id)
        except Classroom.DoesNotExist:
            messages.error(request, f"Učebňa s id {input_room_id} neexistuje.")
            redirect('search')
        reservation_candidate = Reservation(classroom=classroom, date=input_date, lesson=input_lesson,
                                            teacher=teacher)
        context = {
            "result": reservation_candidate,
            "action": "create"
        }
        return render(request, "reservation_form.html", context)

    @method_decorator(login_required, name='dispatch')
    def post(self, request, *args, **kwargs):
        input_date, input_lesson, input_room_id, _, parsing_error = parse_inputs(
            REST_method=request.POST)
        if not parsing_error["is_valid"]:
            messages.error(request, parsing_error["errors"][0])
            return redirect('search')
        if (input_date is None) or (input_lesson is None) or (input_room_id is None):
            messages.error(request, "Chýbajúce argumenty (dátum, učebňa alebo hodina) pre rezerváciu učebne.")
            return redirect('search')
        teacher = f'{request.user.first_name} {request.user.last_name}'
        is_available, search_errors = is_classroom_available(input_date, input_lesson, input_room_id)
        if not search_errors["is_valid"]:
            messages.error(request, parsing_error["errors"][0])
            return redirect('search')
        if is_available:
            classroom = None
            try:
                classroom = Classroom.objects.get(id=input_room_id)
            except Classroom.DoesNotExist:
                messages.success(request, f"Učebňa s id {input_room_id} neexistuje.")
                redirect('search')
            Reservation.objects.create(date=input_date, classroom=classroom, lesson=input_lesson, teacher=teacher)
            return redirect("reservation-list")
        else:
            messages.error(request, "Učebňa už nie je voľná pre Vami zadaný deň a hodinu.")
            return redirect("search")


class ReservationDeleteView(ReservationBaseView, View):

    @method_decorator(login_required, name='dispatch')
    def post(self, request, *args, **kwargs):
        reserved_id = request.POST.get("reservation_id")
        teacher = f'{request.user.first_name} {request.user.last_name}'
        try:
            reservation = Reservation.objects.get(id=reserved_id)
            if reservation.teacher != teacher and not request.user.is_superuser:
                messages.error(request, f"Nedostatočné oprávnenie vymazať rezerváciu s id {id}.")
                return redirect('reservation-list')
            reservation.delete()
        except Reservation.DoesNotExist:
            messages.error(request, f"Rezervácia s {id} neexistuje.")
            return redirect('reservation-list')

        return redirect('reservation-list')


class ReservationDetailView(ReservationBaseView, View):
    @method_decorator(login_required, name='dispatch')
    def get(self, request, *args, **kwargs):
        try:
            id = kwargs.get("id")
        except TypeError:
            messages.error(request, "Chýbajúci parameter id pre rezerváciu.")
            return redirect('reservation-list')
        try:
            reservation = Reservation.objects.get(id=id)
            teacher = f'{request.user.first_name} {request.user.last_name}'
            if reservation.teacher != teacher and not request.user.is_superuser:
                messages.error(request, f"Nedostatočné oprávnenie na prezretie rezervácie s id {id}.")
                return redirect('reservation-list')
        except Reservation.DoesNotExist:
            messages.error(request, f"Rezervácia s {id} neexistuje.")
            return redirect('reservation-list')
        context = {
            "result": reservation,
            "action": "delete"
        }
        return render(request, "reservation_form.html", context)

templates/home.html
{% extends "skeleton.html" %}
{% load static %}
<head>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
{% block content %}

    <div class="main_image">
        <img src="{% static 'assets/iCLASS.png' %}" class="home_logo" alt="iClass">
    </div>
    <div class="form-fieldset-one-row">
        <div class="submit-button">
            <a href="/search">Hľadaj</a>
        </div>
        <div class="submit-button">
            <a href="/reservations">Rezervácie</a>
        </div>
    </div>


{% endblock %}

templates/login.html
{% extends "skeleton.html" %}
{% load static %}

{% block content %}
    <div class="container">
        {% if messages %}
            {% for message in messages %}

                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"
                            aria-hidden="true" onclick="closeMessage()"></button>
                    {{ message }}
                </div>

            {% endfor %}
        {% endif %}
    </div>
    <div class="res_header">
    Prihlásenie
    <hr style="width:50%; margin: auto; background:black;" />

    <div class="form-center-page">
        <form method=POST action="/login/">
            {% csrf_token %}
            <fieldset>
                <div class="form-row">
                    <label for="username">Prihlasovacie meno</label>
                </div>
                <div class="form-row">
                    <input type="text" id="username" name="username">
                </div>
                <div class="form-row">
                    <label for="password">Heslo
                    </label>
                </div>
                <div class="form-row">
                    <input type="password" id="password" name="password">
                </div>
                {% if request.GET.next %}
                    <label for="nextUrlText" hidden>Ciel
                        <input type="text" name="next" id="nextUrlText" value="{{ request.GET.next }}"
                               hidden></label>
                {% endif %}
                <div class="form-row">
                    <input type="submit" value="Prihlásiť" class="submit-button">
                </div>
            </fieldset>
        </form>
    </div>
{% endblock %}

templates/reservation_form.html
{% extends "skeleton.html" %}
{% load static %}

{% block content %}

    <div class="res_header">
        Rezervácia
        <hr style="width:50%; margin: auto; background:black;"/>
    </div>
    <div class="form-center-page">
        <form method="POST" id="reservation_form" class="form-custom-input"
                {% if action == "delete" %}
              action="/reservations/delete/"
                {% endif %}>
            {% csrf_token %}
            <fieldset>
                <div class="">
                    {% if action == "delete" %}
                        <div class="form-one-row-left">
                            <label for="date_id">Číslo rezervácie:
                                <input type="number" id="reservation_id" name="reservation_id"
                                       value="{{ result.id }}"
                                       required readonly>
                            </label>

                        </div>
                    {% endif %}
                    <div class="form-one-row-left">
                        <label for="date_id">Deň:
                            <input type="date" id="date_id" name="date"
                                   value="{{ result.date|date:"Y-m-d" }}" required readonly>
                        </label>
                    </div>
                    <div class="form-one-row-left">
                        <label for="classroom_id">Učebňa:
                            {{ result.classroom.name }}
                            <input type="number" name="classroom" id="classroom_name"
                                   value="{{ result.classroom.id }}" hidden required readonly>

                        </label>
                    </div>

                    <div class="form-one-row-left">
                        <label for="lesson_id">Hodina:
                            <input type="number" id="lesson_id" name="lesson" min="0" max="8"
                                   value="{{ result.lesson }}" required readonly>
                        </label>
                    </div>
                    <div class="form-one-row-left">
                        <label for="lesson_id">Používateľ:
                            <input type="text" id="teacher_id" name="teacher" value="{{ result.teacher }}"
                                   required readonly>
                        </label>
                    </div>
            </fieldset>
            <div class="form-row">
                {% if action == "create" %}
                    <input type="submit" id="createSubmit" value="Rezervovať" class="submit-button">
                {% else %}
                    <input type="submit" id="deleteSubmit" value="Vymazať" class="submit-button">
                {% endif %}
            </div>
        </form>
    </div>
{% endblock %}

templates/reservation_list.html
{% extends "skeleton.html" %}
{% load static %}

{% block content %}
    <div class="container">
        {% if messages %}
            {% for message in messages %}

                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"
                            aria-hidden="true" onclick="closeMessage()"></button>
                    {{ message }}
                </div>

            {% endfor %}
        {% endif %}
    </div>

    <div class="res_header">
        Vaše rezervácie
        <hr style="width:50%; margin: auto; background:black;"/>
        <div class="form-center-page">

            <table class="reservations">
                <tr>
                    <th>Dátum</th>
                    <th>Učebňa</th>
                    <th>Hodina</th>
                </tr>

                {% for reserve in reservations %}
                    <tr onclick="window.location.href='/reservations/{{ reserve.id }}'">
                        <td>{{ reserve.date }}</td>
                        <td>{{ reserve.classroom.name }}</td>
                        <td>{{ reserve.lesson }}</td>
                    </tr>
                {% endfor %}
            </table>
        </div>

    </div>
{% endblock %}

templates/search_form.html
{% extends "skeleton.html" %}
{% load static %}

{% block content %}
    <div class="container">
        {% if messages %}
            {% for message in messages %}

                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"
                            aria-hidden="true" onclick="closeMessage()"></button>
                    {{ message }}
                </div>

            {% endfor %}
        {% endif %}
    </div>

    <div class="forms_block">
        <br>
        <form action="" id="search_form">
            <fieldset>
                <div class="form-fieldset-one-row">
                    <label for="date_id">Deň:
                        <input type="date" id="date_id" name="date" value="{{ search_params.date|date:"Y-m-d" }}"
                               required>
                    </label>

                    <label for="classroom_id">Učebňa:
                        <input list="classroom" name="classroom" id="classroom_id" value="{{ search_params.room }}">
                    </label>

                    <datalist id="classroom">
                        {% for room in classrooms %}
                            <option value={{ room.id }}>{{ room.name }}</option>
                        {% endfor %}
                    </datalist>
                    <label for="lesson_id">Hodina
                        <input type="number" id="lesson_id" name="lesson" min="0" max="8"
                               value="{{ search_params.lesson }}">
                    </label>
                </div>
            </fieldset>


            <br>
            <fieldset id="equipment_id">
                <div class="form-fieldset-one-row">
                    <label class="form-control">
                        <input type="checkbox" id="interactive_board" name="interactive_board" value="1"
                               {% if search_params.equipment_params.interactive_board %}checked {% endif %}/>
                        Interaktívna tabuľa</label>

                    <label class="form-control">
                        <input type="checkbox" id="data_projector" name="data_projector" value="1"
                               {% if search_params.equipment_params.data_projector %}checked {% endif %}/>
                        Data projektor</label>

                    <label class="form-control">
                        <input type="checkbox" id="ethernet_cable" name="ethernet_cable" value="1"
                               {% if search_params.equipment_params.ethernet_cable %}checked {% endif %}/>
                        Internetový kábel</label>
                    <label class="form-control">
                        <input type="checkbox" id="sink" name="sink" value="1"
                               {% if search_params.equipment_params.sink %}checked {% endif %}/>
                        Umývadlo</label>
                    <label class="form-control">
                        <input type="checkbox" id="flip_chart" name="flip_chart" value="1"
                               {% if search_params.equipment_params.flip_chart %}checked {% endif %}/>
                        Flip chart</label>
                    <label class="form-control">
                        <input type="checkbox" id="teacher_notebook" name="teacher_notebook" value="1"
                               {% if search_params.equipment_params.teacher_notebook %}checked {% endif %}/>
                        Učiteľský notebook</label>
                    <label class="form-control">
                        <input type="checkbox" id="teacher_pc" name="teacher_pc" value="1"
                               {% if search_params.equipment_params.teacher_pc %}checked {% endif %}/>
                        Učiteľský počítač</label>
                </div>
            </fieldset>
            <br>
            <input type="submit" id="formSubmit" value="Hľadať" class="submit-button">
        </form>
    </div>
    {% if with_results %}
        {% if result_type == "classroom_list" %}
            <div class="name_of_classroom">{{ search_params.lesson }}.hodina</div>
            <div class="block-container">
                {% for key, value in result.items %}
                    {% if value.occupancy %}
                        <div class="block-occupied">
                            <div class="flex-item">
                                <span>{{ value.info.name }}</span>
                                <span>Študenti: {{ value.occupancy.0.students }}</span>
                                <span>Učiteľ: {{ value.occupancy.0.teacher }}</span>
                                <span>Predmet: {{ value.occupancy.0.subject }}</span>
                            </div>
                            <div class="flex-item">
                                <p class="equipment">
                                    {% for key, value in value.info.equipment.items %}
                                        {% if value %}
                                            {{ key }} |
                                        {% endif %}
                                    {% endfor %}
                                </p>
                            </div>
                        </div>
                    {% else %}
                        <a class="block-free"
                           href="/reservations/create/?date={{ search_params.date|date:"Y-m-d" }}&classroom={{ value.info.id }}&lesson={{ search_params.lesson }}">
                            <div class="flex-item">
                                <span>{{ value.info.name }}</span>
                                <span>Voľná</span>
                            </div>
                            <div class="flex-item">
                                <div class="equipment">
                                    {% for key, value in value.info.equipment.items %}
                                        {% if value %}
                                            {{ key }} |
                                        {% endif %}
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="flex-item-right">
                                <span>Rezervovať</span>
                            </div>
                        </a>
                    {% endif %}

                {% endfor %}
            </div>
        {% elif result_type == "lesson_list" %}
            <div class="name_of_classroom">{{ search_room.name }}</div>
            <div class="equipment"> Vybavenie:
                {% for key, value in search_room.equipment.items %}
                    {% if value %}
                        {{ key }} |
                    {% endif %}
                {% endfor %}
            </div>
            <div class="block-container">
                {% for key, value in result.items %}
                    {% if value.occupancy %}
                        <div class="block-occupied">
                            <div class="flex-item">
                                <span>{{ key }}.hodina</span>
                                <span>Študenti: {{ value.occupancy.0.students }}</span>
                                <span>Učiteľ: {{ value.occupancy.0.teacher }}</span>
                                <span>Predmet: {{ value.occupancy.0.subject }}</span>
                            </div>
                            <div class="flex-item-right">Obsadená</div>
                        </div>
                    {% else %}
                        <a class="block-free"
                           href="/reservations/create/?date={{ search_params.date|date:"Y-m-d" }}&classroom={{ search_room.id }}&lesson={{ key }}">
                            <div class="flex-item">
                                <span>{{ key }}.hodina</span>
                                <span>Voľná</span>
                            </div>
                            <div class="flex-item-right">
                                <span>Rezervovať</span>
                            </div>
                        </a>
                    {% endif %}
                {% endfor %}
            </div>
        {% elif result_type == "boolean_result" %}
            <div class="name_of_classroom">
                {{ search_room.name }}
                <p class="equipment"> Vybavenie:
                    {% for key, value in search_room.equipment.items %}
                        {% if value %}
                            {{ key }} |
                        {% endif %}
                    {% endfor %}
                </p>
            </div>
            <div class="block-container">
                {% if is_free %}
                    <a href="/reservations/create/?date={{ search_params.date|date:"Y-m-d" }}&classroom={{ search_params.room }}&lesson={{ search_params.lesson }}"
                       class="block-free">
                        <div class="flex-item">
                            <span>{{ search_room.name }}</span>
                            <span>{{ search_params.lesson }}.hodina</span>
                            <span>Voľná</span>
                        </div>
                        <div class="flex-item-right">
                            <span>Rezervovať</span>
                        </div>
                    </a>
                {% else %}
                    {% for res in result %}
                        <div class="block-occupied">
                            <div class="flex-item">
                                <span>{{ res.lesson }}.hodina</span>
                                <span>Študenti: {{ res.students }}</span>
                                <span>Učiteľ: {{ res.teacher }}</span>
                                <span>Predmet: {{ res.subject }}</span>
                            </div>
                            <div class="flex-item-right">Obsadená</div>

                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        {% endif %}
    {% else %}
        <!--
        tu nechat volne miesto, to ked pouzivatel ide hladat a nema este ziadne vysledky
        -->
    {% endif %}

    <script src="{% static 'js/form_handler.js' %}"></script>
{% endblock %}

templates/skeleton.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width initial-scale=1">
    <title>iClass</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %} ">
    <link rel="stylesheet" href="{% static 'css/enchanced_style.css' %} ">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{% static 'js/message_handler.js' %}"></script>
</head>
<body>
<header>
    <a href="/"><img src="{% static 'assets/name_logo.png' %}" alt="iclass_logo" class="header_logo"></a>
    {% if request.user.is_authenticated %}
        <p class="username">{{ request.user.username }}
            <img src="{% static 'assets/user_icon.png' %}" class="user_icon" alt="user_icon">
            <a href="/logout" class="logout_text">Odhlásenie</a>
        </p>
    {% else %}
        <a href="/login" class="login_text">Prihlásenie</a>
    {% endif %}
</header>
<div class="transition_in">
{% block content %}
{% endblock %}
</div>
<footer>
    <table class="footer_links">
        <tr>
            <td><a href="/" class="home_pointer">Domov</a></td>
            <td><a href="/search" class="home_pointer">Hľadaj</a></td>
            <td><a href="/reservations" class="home_pointer">Rezervácie</a></td>
        </tr>
    </table>
</footer>
</body>
</html>